### ISSUE TITLE
`chainHead_v1_call` always yields `operationInaccessible` events for `DryRunApi_dry_run_call`

### ISSUE THREAD

**Issue by josepot** [smol-dot/smoldot#2035]
The `DryRunApi_dry_run_call` runtime-API always yields an `operationInaccessible` event, making it unusable with smoldot.

This runtime-api is very useful for calculating the XCM delivery fees and for many other use-cases.

This issue is preventing the [following PR](https://github.com/kheopswap/kheopswap/pull/40) from being merged.

I have created the [following repo](https://github.com/josepot/dry-run-smoldot-issue) to reproduce this issue, using [this code](https://github.com/josepot/dry-run-smoldot-issue/blob/main/index.ts) (the exact same code works with a WebSocket provider).

The logs that I captured after running that code:
- [Wire logs](https://github.com/josepot/dry-run-smoldot-issue/blob/51ebb523214cbdb84c74d68f51f4dc782fcdc5c3/wire-logs.txt)
- [Smoldot logs](https://github.com/josepot/dry-run-smoldot-issue/blob/51ebb523214cbdb84c74d68f51f4dc782fcdc5c3/smoldot-logs.txt)

I'm more than willing to test this problem with a custom build of smoldot and/or to provide any other assistance to get to the bottom of this issue.

**Comment by tomaka** [comment]
Here's a branch that you can please use: https://github.com/tomaka/smoldot/tree/debug-2035
It will generate the logs that interest me.

**Comment by 0xKheops** [comment]
Thank you so much to both of you for your help with this problem, and for solving it so fast!

**Comment by josepot** [comment]
Unfortunately, the issue persists with the latest version of smoldot. So, I think that this issue was prematurely closed.

The logs:
- [smoldot-logs.txt](https://github.com/user-attachments/files/17801468/smoldot-logs.txt)
- [wire-logs.txt](https://github.com/user-attachments/files/17801470/wire-logs.txt)

**Comment by tomaka** [comment]
There's more than one bug, then. I've updated my branch above.

**Comment by josepot** [comment]
New logs with the custom build:

- [smoldot-logs.txt](https://github.com/user-attachments/files/17802750/smoldot-logs.txt)
- [Uploading wire-logs.txt…]()

**Comment by tomaka** [comment]
Could you try again with https://github.com/smol-dot/smoldot/pull/2039 ? (or with the main branch, as I'm going to merge that PR no matter what)

I've also already merged https://github.com/smol-dot/smoldot/pull/2039 onto the branch above in case it fails again.

**Comment by josepot** [comment]
> Before I release a version, could you try again with #2039 ? (or with the main branch, as I'm going to merge that PR no matter what)
> 
> I've also already merged #2039 onto the branch above in case it fails again.

Still not working, the logs:
- [smoldot-logs.txt](https://github.com/user-attachments/files/17803811/smoldot-logs.txt)
- [wire-logs.txt](https://github.com/user-attachments/files/17803810/wire-logs.txt)

**Comment by josepot** [comment]
> Opened #2041 and updated the branch above.

Third time's the charm!!! It works! Thanks @tomaka !

**Comment by josepot** [comment]
Unfortunately, we just noticed that this issue still exists with kusama 😞 

- [smoldot-logs.txt](https://github.com/user-attachments/files/17817705/smoldot-logs.txt)
- [wire-logs.txt](https://github.com/user-attachments/files/17817710/wire-logs.txt)

**Comment by tomaka** [comment]
The debug-2035 branch is additional logs about a specific bug. I need the generic logs again.

**Comment by josepot** [comment]
> The debug-2035 branch is additional logs about a specific bug. I need the generic logs again.

here you go, generic logs of the same code as before but running it against the Kusama relay-chain and using the latest main on smoldot:
- [smoldot-logs.txt](https://github.com/user-attachments/files/17830757/smoldot-logs.txt)
- [wire-logs.txt](https://github.com/user-attachments/files/17830759/wire-logs.txt)

**Comment by tomaka** [comment]
This new problem is the same as #1985, so I'm going to close this one again.
